[en]
title = "QA Discovery"
weight = 1
LanguageName = "ğŸ‡¬ğŸ‡§EN"
contentDir = "content/english"

[zh-CN]
title = "QA Discovery"
description = "è´¨é‡åˆ†æå¸ˆï¼Œè€Œéè´¨é‡ä¿è¯å¸ˆ"
contentDir = "content/zh" 
weight = 2
LanguageName = "ğŸ‡¨ğŸ‡³ä¸­æ–‡"
